apiVersion: batch/v1
kind: Job
metadata:
  name: migration-job
spec:
  template:
    spec:
      containers:
        - name: migration-container
          image: diogosilvasantana/maestro_api:latest  # Use a imagem que contenha suas migrações
          command: ["./gradlew", "flywayMigrate"]  # Comando para rodar as migrações
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://svc-postgres:5432/maestro  # URL do banco de dados
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: maestro-secrets  # Nome do segredo onde está o nome de usuário
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: maestro-secrets  # Nome do segredo onde está a senha
                  key: password
      restartPolicy: Never
  backoffLimit: 1  # Isso garante que o Job seja executado apenas uma vez
