apiVersion: v1
kind: Pod
metadata:
  name: pgadmin-pod
spec:
  containers:
    - name: pgadmin-container
      image: dpage/pgadmin4
      ports:
        - containerPort: 5050
      env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: admin@admin.com
        - name: PGADMIN_DEFAULT_PASSWORD
          value: admin
      volumeMounts:
        - name: pgadmin-data
          mountPath: /var/lib/pgadmin
        - name: pgadmin-servers-config
          mountPath: /pgadmin4/servers.json
      readinessProbe:
        httpGet:
          path: /login
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 5
  volumes:
    - name: pgadmin-data
      emptyDir: {}
    - name: pgadmin-servers-config
      hostPath:
        path: /scripts/pgadmin/servers.json