apiVersion: v1
kind: Pod
metadata:
  name: postgres-db
  labels:
    app: postgres-db
spec:
  containers:
    - name: postgres-db
      image: bitnami/postgresql:latest
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRESQL_USERNAME
          value: admin
        - name: POSTGRESQL_PASSWORD
          value: admin
        - name: POSTGRESQL_DATABASE
          value: maestro
    - name: postgres-db-redis
      image: redis:latest
      ports:
        - containerPort: 6379
