apiVersion: v1  
kind: Service
metadata:
  name: svc-maestro-app
  namespace: maestro
spec:
  type: NodePort
  ports:
    - port: 80      
      nodePort: 31000
      targetPort: 8080
  selector:
    app: maestro-app