apiVersion: v1
kind: Service
metadata:
  name: svc-maestro-app
  labels:
    app: svc-maestro-app
spec:
  selector:
    app: maestro-app
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080



#       apiVersion: v1  
# kind: Service
# metadata:
#   name: svc-proart-api
# spec:
#   type: NodePort
#   ports:
#     - port: 80      
#       nodePort: 31000
#       targetPort: 3333
#   selector:
#     app: proart-api-redis