name: CD

on:
  pull_request_target:
    types: [closed]
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      packages: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Replace files
        run: |          
          sed -i -e 's/<ACCOUNT_ID>/${{secrets.ACCOUNT_ID}}/g' .github/k8s/02-deployment-api.yaml

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: us-east-1

      - name: Update kube config
        run: aws eks update-kubeconfig --name ${{secrets.CLUSTER_NAME}} --region us-east-

      - name: Deploy to Amazon EKS
        run: |
          kubectl apply -f .github/k8s/01-namespace.yaml
          kubectl apply -f .github/k8s/02-deployment-api.yaml
          kubectl apply -f .github/k8s/03-service-api.yaml
          kubectl apply -f .github/k8s/04-ingress-api.yaml